[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer-runs = 999999999

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
